SRCROOT = ..

# compilation flags for gdb
#CFLAGS  = -O1 -g
#ASFLAGS = -g 

# object files
OBJS=  $(STARTUP) main.o
OBJS+= stm32f10x_gpio.o stm32f10x_rcc.o stm32f10x_usart.o tasks.o port.o list.o heap_4.o timers.o queue.o

# include common make file
include $(SRCROOT)/Makefile.common


