version: 2.1

jobs:
  build:
    working_directory: ~/project
    machine:
      image: ubuntu-2004:202010-01
    # Add steps to the job
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

      - run:
          name: "Install dependencies"
          command: |
            sudo apt update
            sudo apt install gcc-arm-none-eabi -y
      - run:
          name: "Compile hello world app"
          command: |
            cd ~/project/Src/FreeRTOS-hello/
            make
